### ISSUE TITLE
Please update types of sdk

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#103]
![image](https://user-images.githubusercontent.com/108503412/219343513-9bc8625b-a729-475f-b333-d3a2447fb7dd.png)
I used this api and got this error, but i found in response the event get more data. Please fix this
![image](https://user-images.githubusercontent.com/108503412/219343872-10d0f151-1566-46df-a113-1057aac6fdc7.png)

**Comment by ryukato** [comment]
Hello and thank you for letting us know the issue. But I think that's not an issue because all the events will be typed into [`TransactionEvent`](https://github.com/line/line-blockchain-developers-sdk-js/blob/5436d621ff2676424544197789ef9367f9d6e73f/lib/tx-core-models.ts#L8), that is super type(interface) and it has only properties(`eventName`) can have concrete event types. 
So I suggest the ways below to get the `tokenIds` property. 

```
if(statusCode === "1000") {
  const tokenValue = responseData?.events[0]["tokenIds"] as string;
}
```

if you want to be more carefull, then following codes are available.
```
if(statusCode === "1000") {
  const nftMintedEvents = lbdTxResult.txEvents.filter(event => { event.eventName === "EventCollectionNftMinted"});
    if (nftMintedEvents.length > 0) {
      const tokenValues = (nftMintedEvents[0] as EventCollectionNftMinted).tokenIds;
      // handle with tokenValues
    }
}
```

if you want a sort of a utility function to get expected type of an event from transaction result, then please let us know. We will see and provide such features.

**Comment by ryukato** [comment]
I will close this issue since it does not look a bug. But feel free you can open this any time if you have any question or something else.
