### ISSUE TITLE
sync data from line nft store to my own store

### ISSUE THREAD

**Issue by ducnh-wano** [line/line-blockchain-developers-sdk-js#57]
I am creating my own NFT store base on line blockchain, but i have an issue that when my nft was bought or sold on LINE NFT STORE i cannot sync data to my NFT store, in Ethereum i can read logs of blockchain and sync data from blockchain to my custom nft market place. can you give me some solutions. Many thanks.

**Comment by ryukato** [comment]
I hope you don't mind that I have a couple of questions about your inquiry. 
It sounds like you want to do somthing as followgins.
* Do a sort of update to your another dApp on Ethereum and the update has to be triggered when a NFT on LINE NFT store is sold,
* Develop an application to do the sync job, using this library.
* But it's hard to get what is `tx-hash` for the transation, which is about NFT sold. (I guess this is critical issue for you)

I appreciate if you check the above and let me know it is correct or not.

**Comment by ducnh-wano** [comment]
**Do a sort of update to your another dApp on Ethereum and the update has to be triggered when a NFT on LINE NFT store is sold,** -> when i work with ethereum i created my own cron-job server, this server will run every 30 seconds to read data from logs of blockchain (acctually it is what event of smart of smart contract emit and this server will read it and process logical problem and sync to my DB so data from blockchain always sync with my data backend)

**Develop an application to do the sync job, using this library.** -> Yes i m using this library to develop an backend for a kind of custom NFT store. i want the NFT was created by my App also sell or buy on LINE STORE.

**But it's hard to get what is tx-hash for the transation, which is about NFT sold. (I guess this is critical issue for you)** -> yeah, right now i dont know how to get the tx-hash which was happened on LINE STORE, so my App is not correct. thank you for yor supporting alot.

**Comment by ryukato** [comment]
Well I can see what you want but for now we have callback for a tx-result to external application like your dApp or backend. Using the callback, your application can receive tx-result for a transactionn, which is made from your one of service wallet. I am sorry but I know that can not solve your issue for now. 

We will check and consider to provide an API to response list of transactions for a specific token(service or item-token).
I guess it could help your issue, otherwise please let me know.

example of the API
* request
  * GET /v1/[service-tokens | item-tokens]/{contractId}?tokenType=xxxxxxxx&tokenIndex=xxxxxxxx&limit=50&orderBy=asc&page=1
   > 
   > 
   > tokenType and index are only for item-token 
* response
  * list of tx-hash (or tx-result)

**Comment by ryukato** [comment]
I will close this issue because there hasn't been re-action and a way to support for now.
